Optimized ContestantApiController
nerdakademie/stupa-wahltool pull request #26
Opened 2017-02-27 01:26 UTC by phibsi

Add node_module cross-env;
Split up method ContestantApiController.find;
Add StringHelper;
Add string validation to ContestantApiController

2017-02-27 07:01 UTC, mwohlert commented
Hi,

danke für deinen PR. Sieht soweit auch gut aus.
Könntest du den veränderten Pfad, dann auch in https://github.com/nerdakademie/stupa-wahltool/blob/development/src/client/component/pages/ContestantEdit.jsx#L146 anpassen, damit der PR vollständig ist?

2017-02-27 07:14 UTC, mwohlert requested changes
Hi,

danke für deinen PR. Sieht soweit auch gut aus.
Könntest du den veränderten Pfad, dann auch in https://github.com/nerdakademie/stupa-wahltool/blob/development/src/client/component/pages/ContestantEdit.jsx#L146 anpassen, damit der PR vollständig ist?

2017-02-27 18:15 UTC, phibsi commented
Dies wurde bereits mit Commit https://github.com/phibsi/stupa-wahltool/commit/07321e8ef3af6e28c16c10eedbf80278f73be33f getan:
https://github.com/phibsi/stupa-wahltool/blob/development/src/client/component/pages/ContestantEdit.jsx#L146

2017-02-28 07:12 UTC, mwohlert approved these changes

2017-02-28 07:29 UTC, merged